course_name = "智能证券投资"
course_code = "COMP3042"

notices = ""

lecturers = []

textbooks = []

online_resources = []

course = []

exam = []

lab = []

advice = []

schedule = []

related_links = []

misc = []